//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talifun.Commander.Command.Video.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Talifun.Commander.Command.Video.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Specified.
        /// </summary>
        public static string AspectRatio_NotSpecified {
            get {
                return ResourceManager.GetString("AspectRatio_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16:10.
        /// </summary>
        public static string AspectRatio_RatioOf16by10 {
            get {
                return ResourceManager.GetString("AspectRatio_RatioOf16by10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16:9.
        /// </summary>
        public static string AspectRatio_RatioOf16By9 {
            get {
                return ResourceManager.GetString("AspectRatio_RatioOf16By9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4:3.
        /// </summary>
        public static string AspectRatio_RatioOf4By3 {
            get {
                return ResourceManager.GetString("AspectRatio_RatioOf4By3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC.
        /// </summary>
        public static string AudioConversionType_Aac {
            get {
                return ResourceManager.GetString("AudioConversionType_Aac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC3.
        /// </summary>
        public static string AudioConversionType_Ac3 {
            get {
                return ResourceManager.GetString("AudioConversionType_Ac3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3.
        /// </summary>
        public static string AudioConversionType_Mp3 {
            get {
                return ResourceManager.GetString("AudioConversionType_Mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        public static string AudioConversionType_NotSpecified {
            get {
                return ResourceManager.GetString("AudioConversionType_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis.
        /// </summary>
        public static string AudioConversionType_Vorbis {
            get {
                return ResourceManager.GetString("AudioConversionType_Vorbis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown audio conversion type.
        /// </summary>
        public static string ErrorMessageUnknownAudioConversionType {
            get {
                return ResourceManager.GetString("ErrorMessageUnknownAudioConversionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown video conversion type.
        /// </summary>
        public static string ErrorMessageUnknownVideoConversionType {
            get {
                return ResourceManager.GetString("ErrorMessageUnknownVideoConversionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a name.
        /// </summary>
        public static string ValidatorMessageVideoConversionElementNameMandatory {
            get {
                return ResourceManager.GetString("ValidatorMessageVideoConversionElementNameMandatory", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap VideoConversionElement {
            get {
                object obj = ResourceManager.GetObject("VideoConversionElement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap VideoConversionElementCollection {
            get {
                object obj = ResourceManager.GetObject("VideoConversionElementCollection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flv.
        /// </summary>
        public static string VideoConversionType_Flv {
            get {
                return ResourceManager.GetString("VideoConversionType_Flv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H. 264.
        /// </summary>
        public static string VideoConversionType_H264 {
            get {
                return ResourceManager.GetString("VideoConversionType_H264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Specified.
        /// </summary>
        public static string VideoConversionType_NotSpecified {
            get {
                return ResourceManager.GetString("VideoConversionType_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theora.
        /// </summary>
        public static string VideoConversionType_Theora {
            get {
                return ResourceManager.GetString("VideoConversionType_Theora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPX.
        /// </summary>
        public static string VideoConversionType_Vpx {
            get {
                return ResourceManager.GetString("VideoConversionType_Vpx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XVid.
        /// </summary>
        public static string VideoConversionType_Xvid {
            get {
                return ResourceManager.GetString("VideoConversionType_Xvid", resourceCulture);
            }
        }
    }
}
