//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talifun.Commander.Command.Image.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Talifun.Commander.Command.Image.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project name=\&quot;{0}\&quot;&gt;&lt;{1}&gt;&lt;{2} name=\&quot;{3}\&quot;&gt; height is required when resize mode is - {4}.
        /// </summary>
        public static string ErrorMessageHeightIsRequiredForResizeMode {
            get {
                return ResourceManager.GetString("ErrorMessageHeightIsRequiredForResizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project name=\&quot;{0}\&quot;&gt;&lt;{1}&gt;&lt;{2} name=\&quot;{3}\&quot;&gt; width is required when resize mode is - {4}.
        /// </summary>
        public static string ErrorMessageWidthIsRequiredForResizeMode {
            get {
                return ResourceManager.GetString("ErrorMessageWidthIsRequiredForResizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Gravity_Center {
            get {
                return ResourceManager.GetString("Gravity_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string Gravity_East {
            get {
                return ResourceManager.GetString("Gravity_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string Gravity_North {
            get {
                return ResourceManager.GetString("Gravity_North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North East.
        /// </summary>
        public static string Gravity_NorthEast {
            get {
                return ResourceManager.GetString("Gravity_NorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North West.
        /// </summary>
        public static string Gravity_NorthWest {
            get {
                return ResourceManager.GetString("Gravity_NorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string Gravity_South {
            get {
                return ResourceManager.GetString("Gravity_South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South East.
        /// </summary>
        public static string Gravity_SouthEast {
            get {
                return ResourceManager.GetString("Gravity_SouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South West.
        /// </summary>
        public static string Gravity_SouthWest {
            get {
                return ResourceManager.GetString("Gravity_SouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string Gravity_West {
            get {
                return ResourceManager.GetString("Gravity_West", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap ImageConversionElement {
            get {
                object obj = ResourceManager.GetObject("ImageConversionElement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ImageConversionElementCollection {
            get {
                object obj = ResourceManager.GetObject("ImageConversionElementCollection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF.
        /// </summary>
        public static string ResizeImageType_GIF {
            get {
                return ResourceManager.GetString("ResizeImageType_GIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPG.
        /// </summary>
        public static string ResizeImageType_JPG {
            get {
                return ResourceManager.GetString("ResizeImageType_JPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use orginal format.
        /// </summary>
        public static string ResizeImageType_Orginal {
            get {
                return ResourceManager.GetString("ResizeImageType_Orginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG.
        /// </summary>
        public static string ResizeImageType_PNG {
            get {
                return ResourceManager.GetString("ResizeImageType_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area To Fit.
        /// </summary>
        public static string ResizeMode_AreaToFit {
            get {
                return ResourceManager.GetString("ResizeMode_AreaToFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut To Fit.
        /// </summary>
        public static string ResizeMode_CutToFit {
            get {
                return ResourceManager.GetString("ResizeMode_CutToFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Height.
        /// </summary>
        public static string ResizeMode_FitHeight {
            get {
                return ResourceManager.GetString("ResizeMode_FitHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Maximum Height.
        /// </summary>
        public static string ResizeMode_FitMaximumHeight {
            get {
                return ResourceManager.GetString("ResizeMode_FitMaximumHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Maximum Width.
        /// </summary>
        public static string ResizeMode_FitMaximumWidth {
            get {
                return ResourceManager.GetString("ResizeMode_FitMaximumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Minimum Height.
        /// </summary>
        public static string ResizeMode_FitMinimumHeight {
            get {
                return ResourceManager.GetString("ResizeMode_FitMinimumHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Minimum Width.
        /// </summary>
        public static string ResizeMode_FitMinimumWidth {
            get {
                return ResourceManager.GetString("ResizeMode_FitMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Width.
        /// </summary>
        public static string ResizeMode_FitWidth {
            get {
                return ResourceManager.GetString("ResizeMode_FitWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not resize.
        /// </summary>
        public static string ResizeMode_None {
            get {
                return ResourceManager.GetString("ResizeMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        public static string ResizeMode_Stretch {
            get {
                return ResourceManager.GetString("ResizeMode_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string ResizeMode_Zoom {
            get {
                return ResourceManager.GetString("ResizeMode_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a name.
        /// </summary>
        public static string ValidatorMessageImageConversionElementNameMandatory {
            get {
                return ResourceManager.GetString("ValidatorMessageImageConversionElementNameMandatory", resourceCulture);
            }
        }
    }
}
