//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talifun.Commander.Command.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Talifun.Commander.Command.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Commander {
            get {
                object obj = ResourceManager.GetObject("Commander", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        public static string ContextMenuAddElement {
            get {
                return ResourceManager.GetString("ContextMenuAddElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string ContextMenuDeleteElement {
            get {
                return ResourceManager.GetString("ContextMenuDeleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        public static string ContextMenuNewElement {
            get {
                return ResourceManager.GetString("ContextMenuNewElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App settings {0} required .
        /// </summary>
        public static string ErrorMessageAppSettingRequired {
            get {
                return ResourceManager.GetString("ErrorMessageAppSettingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find &lt;project&gt; for &lt;fileMatch&gt; element.
        /// </summary>
        public static string ErrorMessageCannotFindProjectForFileElement {
            get {
                return ResourceManager.GetString("ErrorMessageCannotFindProjectForFileElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project name=\&quot;{0}\&quot;&gt;&lt;folders&gt;&lt;folder name=\&quot;?\&quot;&gt;&lt;fileMatches&gt;&lt;fileMatch name=\&quot;{1}\&quot;&gt; conversionSettingsKey specified points to non-existant &lt;{2}&gt; - {3}.
        /// </summary>
        public static string ErrorMessageCommandConversionSettingKeyPointsToNonExistantCommand {
            get {
                return ResourceManager.GetString("ErrorMessageCommandConversionSettingKeyPointsToNonExistantCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project name=\&quot;{0}\&quot;&gt;&lt;{1}&gt;&lt;{2} name=\&quot;{3}\&quot;&gt; errorProcessingPath does not exist - {4}.
        /// </summary>
        public static string ErrorMessageCommandErrorProcessingPathDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorMessageCommandErrorProcessingPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project name=\&quot;{0}\&quot;&gt;&lt;{1}&gt;&lt;{2} name=\&quot;{3}\&quot;&gt; outPutPath does not exist - {4}.
        /// </summary>
        public static string ErrorMessageCommandOutPutPathDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorMessageCommandOutPutPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project name=\&quot;{0}\&quot;&gt;&lt;{1}&gt;&lt;{2} name=\&quot;{3}\&quot;&gt; workingPath does not exist - {4}.
        /// </summary>
        public static string ErrorMessageCommandWorkingPathDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorMessageCommandWorkingPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project name=\&quot;{0}\&quot;&gt;&lt;folders&gt;&lt;folders name=\&quot;{1}\&quot;&gt; completedPath does not exist - {2}.
        /// </summary>
        public static string ErrorMessageCompletedPathDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorMessageCompletedPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data read from test file ({0}) was incorrect.
        /// </summary>
        public static string ErrorMessageDataReadFromTestFileWasIncorrect {
            get {
                return ResourceManager.GetString("ErrorMessageDataReadFromTestFileWasIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileMatch attribute conversionSettingsKey=&apos;{0}&apos; does not match any key found in {1} name attributes.
        /// </summary>
        public static string ErrorMessageFileMatchNoMatchingConversionSettingsKey {
            get {
                return ResourceManager.GetString("ErrorMessageFileMatchNoMatchingConversionSettingsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project name=\&quot;{0}\&quot;&gt;&lt;folders&gt;&lt;folder name=\&quot;{1}\&quot;&gt; folderToWatch does not exist - {2}.
        /// </summary>
        public static string ErrorMessageFolderToWatchDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorMessageFolderToWatchDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project name=\&quot;{0}\&quot;&gt;&lt;folders&gt;&lt;folders name=\&quot;{1}\&quot;&gt; folderToWatch is a duplicate, only one watcher per folder branch - {2}.
        /// </summary>
        public static string ErrorMessageFolderToWatchIsADuplicate {
            get {
                return ResourceManager.GetString("ErrorMessageFolderToWatchIsADuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnPropertyChanged was invoked with invalid property name {0}: {0} is not a public property of {1}..
        /// </summary>
        public static string ErrorMessageOnPropertyChangedInvokedWithInvalidPropertyName {
            get {
                return ResourceManager.GetString("ErrorMessageOnPropertyChangedInvokedWithInvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout waiting for lock - RaiseOnCommanderStartedEvent.
        /// </summary>
        public static string ErrorMessageRaiseOnCommandErrorEventTimeoutWaitingForLock {
            get {
                return ResourceManager.GetString("ErrorMessageRaiseOnCommandErrorEventTimeoutWaitingForLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout waiting for lock - CommanderStartedEvent.add.
        /// </summary>
        public static string ErrorMessageRaiseOnCommandErrorEventTimeoutWaitingForLockAdd {
            get {
                return ResourceManager.GetString("ErrorMessageRaiseOnCommandErrorEventTimeoutWaitingForLockAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout waiting for lock - CommanderStartedEvent.remove.
        /// </summary>
        public static string ErrorMessageRaiseOnCommandErrorEventTimeoutWaitingForLockRemove {
            get {
                return ResourceManager.GetString("ErrorMessageRaiseOnCommandErrorEventTimeoutWaitingForLockRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified member {0} was not found on the instance {1}.
        /// </summary>
        public static string ErrorMessageTheSpecifiedMemberWasNotFoundOnInstance {
            get {
                return ResourceManager.GetString("ErrorMessageTheSpecifiedMemberWasNotFoundOnInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete directory {0}.
        /// </summary>
        public static string ErrorMessageUnableToDeleteDirectory {
            get {
                return ResourceManager.GetString("ErrorMessageUnableToDeleteDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find configuration section - {0}.
        /// </summary>
        public static string ErrorMessageUnableToFindConfigurationSection {
            get {
                return ResourceManager.GetString("ErrorMessageUnableToFindConfigurationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find configuration section group - {0}.
        /// </summary>
        public static string ErrorMessageUnableToFindConfigurationSectionGroup {
            get {
                return ResourceManager.GetString("ErrorMessageUnableToFindConfigurationSectionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project name=\&quot;{0}\&quot;&gt;&lt;folders&gt;&lt;folders name=\&quot;{1}\&quot;&gt; workingPath does not exist - {2}.
        /// </summary>
        public static string ErrorMessageWorkingPathDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorMessageWorkingPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FileMatchElement {
            get {
                object obj = ResourceManager.GetObject("FileMatchElement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FileMatchElementCollection {
            get {
                object obj = ResourceManager.GetObject("FileMatchElementCollection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FolderElement {
            get {
                object obj = ResourceManager.GetObject("FolderElement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FolderElementCollection {
            get {
                object obj = ResourceManager.GetObject("FolderElementCollection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saga completed - {0} - {1} - {2}.
        /// </summary>
        public static string InfoMessageSagaCompleted {
            get {
                return ResourceManager.GetString("InfoMessageSagaCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saga started - {0} - {1} - {2}.
        /// </summary>
        public static string InfoMessageSagaStarted {
            get {
                return ResourceManager.GetString("InfoMessageSagaStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ProjectElement {
            get {
                object obj = ResourceManager.GetObject("ProjectElement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ProjectElementCollection {
            get {
                object obj = ResourceManager.GetObject("ProjectElementCollection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ValidationError {
            get {
                object obj = ResourceManager.GetObject("ValidationError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a name.
        /// </summary>
        public static string ValidatorMessageFileMatchElementNameMandatory {
            get {
                return ResourceManager.GetString("ValidatorMessageFileMatchElementNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid regular expression.
        /// </summary>
        public static string ValidatorMessageFolderElementExpressionNotAValidRegularExpression {
            get {
                return ResourceManager.GetString("ValidatorMessageFolderElementExpressionNotAValidRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a name.
        /// </summary>
        public static string ValidatorMessageFolderElementNameMandatory {
            get {
                return ResourceManager.GetString("ValidatorMessageFolderElementNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name has already been used.
        /// </summary>
        public static string ValidatorMessageProjectElementNameHasAlreadyBeenUsed {
            get {
                return ResourceManager.GetString("ValidatorMessageProjectElementNameHasAlreadyBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a name.
        /// </summary>
        public static string ValidatorMessageProjectElementNameMandatory {
            get {
                return ResourceManager.GetString("ValidatorMessageProjectElementNameMandatory", resourceCulture);
            }
        }
    }
}
